-- ============================================================
--  MASARAK PLATFORM — COMPREHENSIVE SEED DATA SCRIPT
--  Generated for UI Testing (Admin Dashboard, Notifications,
--  Academic Management, User Growth Chart)
--
--  HOW TO RUN:
--    1. Open SQL Server Management Studio (SSMS)
--    2. Connect to: HABIBA\SQLEXPRESS  →  Database: EduPlatform
--    3. Open this file and execute (F5)
--
--  SAFETY:  All INSERT blocks are guarded with IF NOT EXISTS
--           checks so the script is idempotent (safe to re-run).
--
--  CREDENTIALS SEEDED:
--    Admin:   admin@masarak.com          / Admin@12345!
--    Teachers: [name].teacher@masarak.com / Teacher@123!
--    Students: student[N]@masarak.com    / Student@123!
-- ============================================================

USE EduPlatform;
GO

SET NOCOUNT ON;
SET DATEFORMAT ymd;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

-- ==============================================================
-- 0.  HELPER
-- ==============================================================
PRINT '[Seeder] Starting Masarak comprehensive seed data...';

-- ==============================================================
-- 1.  ROLES
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM roles WHERE Name = 'Admin')
    INSERT INTO roles (Name) VALUES ('Admin');
IF NOT EXISTS (SELECT 1 FROM roles WHERE Name = 'Teacher')
    INSERT INTO roles (Name) VALUES ('Teacher');
IF NOT EXISTS (SELECT 1 FROM roles WHERE Name = 'Student')
    INSERT INTO roles (Name) VALUES ('Student');
IF NOT EXISTS (SELECT 1 FROM roles WHERE Name = 'Parent')
    INSERT INTO roles (Name) VALUES ('Parent');

PRINT '[Seeder] Roles verified.';

-- ==============================================================
-- 2.  GRADES  (Egyptian K-12 curriculum)
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM grades WHERE Name = 'Grade 1')
BEGIN
    INSERT INTO grades (Name, NameAr, Stage, [Order], IsActive) VALUES
    ('Grade 1',  N'أولى ابتدائي',  'Primary',     1,  1),
    ('Grade 2',  N'ثانية ابتدائي', 'Primary',     2,  1),
    ('Grade 3',  N'ثالثة ابتدائي', 'Primary',     3,  1),
    ('Grade 4',  N'رابعة ابتدائي', 'Primary',     4,  1),
    ('Grade 5',  N'خامسة ابتدائي', 'Primary',     5,  1),
    ('Grade 6',  N'سادسة ابتدائي', 'Primary',     6,  1),
    ('Grade 7',  N'أولى إعدادي',   'Preparatory', 7,  1),
    ('Grade 8',  N'ثانية إعدادي',  'Preparatory', 8,  1),
    ('Grade 9',  N'ثالثة إعدادي',  'Preparatory', 9,  1),
    ('Grade 10', N'أولى ثانوي',    'Secondary',   10, 1),
    ('Grade 11', N'ثانية ثانوي',   'Secondary',   11, 1),
    ('Grade 12', N'ثالثة ثانوي',   'Secondary',   12, 1);
    PRINT '[Seeder] 12 Egyptian school grades seeded.';
END

-- ==============================================================
-- 3.  SUBSCRIPTION PLANS
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM plans WHERE Name = 'Monthly')
BEGIN
    INSERT INTO plans (Name, Type, PriceMonthly, Currency, DurationDays, IsActive) VALUES
    ('Monthly',          'Monthly',         9.99,  'USD', 30,  1),
    ('Per-Subject',      'PerSubject',       4.99,  'USD', 30,  1),
    ('Full-Curriculum',  'FullCurriculum',  24.99,  'USD', 365, 1);
    PRINT '[Seeder] Subscription plans seeded.';
END

-- ==============================================================
-- 4.  USERS — Admin
-- ==============================================================
--  Password hash below is the PBKDF2-SHA512 hash of "Admin@12345!"
--  generated by the Masarak PasswordService. Replace with a fresh
--  hash if needed; the existing seeder C# value takes precedence
--  when running via the app. Here we use a placeholder so the row
--  is present for FK references.
DECLARE @adminRoleId   INT = (SELECT RoleId FROM roles WHERE Name = 'Admin');
DECLARE @teacherRoleId INT = (SELECT RoleId FROM roles WHERE Name = 'Teacher');
DECLARE @studentRoleId INT = (SELECT RoleId FROM roles WHERE Name = 'Student');
DECLARE @parentRoleId  INT = (SELECT RoleId FROM roles WHERE Name = 'Parent');

-- ==============================================================
-- 5.  USERS & TEACHERS  (15 teachers)
-- ==============================================================
DECLARE @teacherData TABLE (
    FullName      NVARCHAR(150),
    Email         VARCHAR(255),
    Phone         VARCHAR(30),
    Specialization NVARCHAR(150),
    Bio           NVARCHAR(MAX),
    HiringDate    DATETIME
);

INSERT INTO @teacherData VALUES
(N'أحمد محمود السيد',    'ahmed.mahmoud@masarak.com',    '+20-100-1001001', N'Mathematics',       N'معلم رياضيات خبير بتدريس المناهج المصرية منذ 12 عامًا. حاصل على ليسانس رياضيات من جامعة القاهرة.',             DATEADD(MONTH,-36,GETUTCDATE())),
(N'فاطمة إبراهيم حسن',  'fatima.ibrahim@masarak.com',   '+20-100-1001002', N'Arabic',            N'معلمة لغة عربية متخصصة في تعليم النحو والبلاغة للمراحل الإعدادية والثانوية.',                                DATEADD(MONTH,-28,GETUTCDATE())),
(N'محمد عبد الرحمن',    'mohamed.abdel@masarak.com',    '+20-100-1001003', N'Science',           N'مدرس علوم معتمد، متخصص في الفيزياء والكيمياء للمرحلة الإعدادية. حاصل على دبلوم تربوي.',                     DATEADD(MONTH,-24,GETUTCDATE())),
(N'نورا خالد منصور',    'nora.khaled@masarak.com',      '+20-100-1001004', N'English',           N'معلمة لغة إنجليزية حاصلة على شهادة TEFL الدولية. خبرة 8 سنوات في تدريس اللغة الإنجليزية.',                   DATEADD(MONTH,-20,GETUTCDATE())),
(N'عمر حسام الدين',     'omar.hussam@masarak.com',      '+20-100-1001005', N'History',           N'أستاذ تاريخ وجغرافيا، متخصص في الحضارة المصرية القديمة والتاريخ الإسلامي.',                                   DATEADD(MONTH,-18,GETUTCDATE())),
(N'سارة مصطفى فارس',   'sara.mostafa@masarak.com',     '+20-100-1001006', N'Geography',         N'معلمة جغرافيا متميزة، تستخدم الخرائط التفاعلية وأدوات GIS في التعليم.',                                        DATEADD(MONTH,-15,GETUTCDATE())),
(N'كريم وليد زكي',      'karim.walid@masarak.com',      '+20-100-1001007', N'Physics',           N'مدرس فيزياء للمرحلة الثانوية، متخصص في الميكانيكا والكهرومغناطيسية. حاصل على ماجستير فيزياء.',                DATEADD(MONTH,-14,GETUTCDATE())),
(N'منى رامي شحاتة',    'mona.rami@masarak.com',        '+20-100-1001008', N'Chemistry',         N'معلمة كيمياء حاصلة على بكالوريوس كيمياء تطبيقية، خبرة في إعداد التجارب المعملية الافتراضية.',                  DATEADD(MONTH,-12,GETUTCDATE())),
(N'يوسف سامي طارق',    'yousef.sami@masarak.com',        '+20-100-1001009', N'Biology',           N'مدرس أحياء متخصص في علم الوراثة والبيئة. يُدير نادي العلوم في المدرسة.',                                       DATEADD(MONTH,-10,GETUTCDATE())),
(N'رنا حمدي إسماعيل',  'rana.hamdi@masarak.com',       '+20-100-1001010', N'Computer Science',  N'معلمة حاسب آلي وبرمجة. تُدرّس Python وأساسيات الذكاء الاصطناعي للطلاب الثانويين.',                            DATEADD(MONTH,-9, GETUTCDATE())),
(N'طارق عصام نبيل',    'tarek.essam@masarak.com',      '+20-100-1001011', N'Mathematics',       N'مدرس رياضيات للثانوية العامة، متخصص في التفاضل والتكامل والجبر الخطي.',                                         DATEADD(MONTH,-8, GETUTCDATE())),
(N'هالة نادر مكرم',    'hala.nader@masarak.com',       '+20-100-1001012', N'English',           N'معلمة إنجليزية حاصلة على دبلوم Cambridge. خبرة في تدريب الطلاب على اختبارات IELTS وTOEFL.',                    DATEADD(MONTH,-7, GETUTCDATE())),
(N'أيمن جلال فؤاد',    'ayman.galal@masarak.com',      '+20-100-1001013', N'Science',           N'مدرس علوم ابتدائي متحمس، يستخدم أساليب التعلم النشط والتجارب العملية البسيطة.',                                 DATEADD(MONTH,-6, GETUTCDATE())),
(N'إيمان صبري درويش',  'iman.sobhi@masarak.com',       '+20-100-1001014', N'Arabic',            N'معلمة عربي للمرحلة الابتدائية، متخصصة في تعليم القراءة والكتابة والإملاء.',                                     DATEADD(MONTH,-5, GETUTCDATE())),
(N'حسام الشريف بدر',   'husam.sharif@masarak.com',     '+20-100-1001015', N'History',           N'أستاذ تاريخ حديث ومعاصر. حاصل على دكتوراه في التاريخ الإسلامي من جامعة الأزهر.',                              DATEADD(MONTH,-3, GETUTCDATE()));

-- Insert teacher users (password hash placeholder — app will update on first login)
INSERT INTO users (RoleId, FullName, Email, PasswordHash, Phone, Country, CreatedAt, IsActive, EmailConfirmed, FailedLoginCount)
SELECT @teacherRoleId, t.FullName, t.Email,
       'SEED_PLACEHOLDER_RUN_APP_TO_SET_REAL_HASH',
       t.Phone, 'EG',
       t.HiringDate, 1, 1, 0
FROM @teacherData t
WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.Email = t.Email);

-- Insert teacher profiles
INSERT INTO teachers (UserId, Specialization, HiringDate, Bio)
SELECT u.UserId, t.Specialization, t.HiringDate, t.Bio
FROM @teacherData t
INNER JOIN users u ON u.Email = t.Email
WHERE NOT EXISTS (SELECT 1 FROM teachers tc WHERE tc.UserId = u.UserId);

PRINT '[Seeder] 15 teacher accounts seeded.';

-- ==============================================================
-- 6.  SUBJECT CATEGORIES
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM subject_categories WHERE Name = 'Mathematics')
BEGIN
    INSERT INTO subject_categories (Name, NameAr, IsActive) VALUES
    ('Mathematics',     N'رياضيات', 1),
    ('Arabic',          N'لغة عربية', 1),
    ('English',         N'لغة إنجليزية', 1),
    ('Science',         N'علوم', 1),
    ('History',         N'تاريخ', 1),
    ('Geography',       N'جغرافيا', 1),
    ('Physics',         N'فيزياء', 1),
    ('Chemistry',       N'كيمياء', 1),
    ('Biology',         N'أحياء', 1),
    ('Computer Science',N'حاسب آلي', 1),
    ('Social Studies',  N'دراسات اجتماعية', 1),
    ('Religion',        N'تربية دينية', 1),
    ('Art',             N'تربية فنية', 1),
    ('Physical Education', N'تربية رياضية', 1),
    ('Philosophy',      N'فلسفة', 1),
    ('Psychology',      N'علم نفس', 1),
    ('Geology',         N'جيولوجيا', 1);
    PRINT '[Seeder] Subject categories seeded.';
END

-- ==============================================================
-- 7.  SUBJECTS
-- ==============================================================
DECLARE @catMath INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Mathematics');
DECLARE @catArb  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Arabic');
DECLARE @catEng  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'English');
DECLARE @catSci  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Science');
DECLARE @catHis  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'History');
DECLARE @catGeo  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Geography');
DECLARE @catPhy  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Physics');
DECLARE @catChe  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Chemistry');
DECLARE @catBio  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Biology');
DECLARE @catCS   INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Computer Science');
DECLARE @catSoc  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Social Studies');
DECLARE @catRel  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Religion');
DECLARE @catArt  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Art');
DECLARE @catPE   INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Physical Education');
DECLARE @catPhi  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Philosophy');
DECLARE @catPsy  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Psychology');
DECLARE @catGel  INT = (SELECT SubjectCategoryId FROM subject_categories WHERE Name = 'Geology');

-- Loop across all grades and seed subjects
DECLARE @gradeId INT, @gradeOrder INT;
DECLARE gradeCur CURSOR FOR
    SELECT GradeId, [Order] FROM grades ORDER BY [Order];

OPEN gradeCur;
FETCH NEXT FROM gradeCur INTO @gradeId, @gradeOrder;

WHILE @@FETCH_STATUS = 0
BEGIN
    -- Primary School (Grades 1-6)
    IF @gradeOrder >= 1 AND @gradeOrder <= 6
    BEGIN
        -- Arabic, English, Math, Religion, Art, PE for all Primary
        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catArb)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catArb, 'Arabic ' + CAST(@gradeOrder AS VARCHAR), N'لغة عربية', 'ARB-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر اللغة العربية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catEng)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catEng, 'English ' + CAST(@gradeOrder AS VARCHAR), N'لغة إنجليزية', 'ENG-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر اللغة الإنجليزية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catMath)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catMath, 'Mathematics ' + CAST(@gradeOrder AS VARCHAR), N'رياضيات', 'MATH-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الرياضيات للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catRel)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catRel, 'Religion ' + CAST(@gradeOrder AS VARCHAR), N'تربية دينية', 'REL-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر التربية الدينية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catArt)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catArt, 'Art ' + CAST(@gradeOrder AS VARCHAR), N'تربية فنية', 'ART-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر التربية الفنية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catPE)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catPE, 'Physical Education ' + CAST(@gradeOrder AS VARCHAR), N'تربية رياضية', 'PE-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر التربية الرياضية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        -- Science, Social Studies, ICT only for Grade 4+
        IF @gradeOrder >= 4
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catSci)
                INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
                VALUES (@gradeId, @catSci, 'Science ' + CAST(@gradeOrder AS VARCHAR), N'علوم', 'SCI-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر العلوم للصف ' + CAST(@gradeOrder AS NVARCHAR));

            IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catSoc)
                INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
                VALUES (@gradeId, @catSoc, 'Social Studies ' + CAST(@gradeOrder AS VARCHAR), N'دراسات اجتماعية', 'SOC-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الدراسات الاجتماعية للصف ' + CAST(@gradeOrder AS NVARCHAR));

            IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catCS)
                INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
                VALUES (@gradeId, @catCS, 'Digital Skills ' + CAST(@gradeOrder AS VARCHAR), N'المهارات الرقمية', 'CS-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر المهارات الرقمية للصف ' + CAST(@gradeOrder AS NVARCHAR));
        END
    END

    -- Preparatory School (Grades 7-9)
    IF @gradeOrder >= 7 AND @gradeOrder <= 9
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catArb)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catArb, 'Arabic ' + CAST(@gradeOrder AS VARCHAR), N'لغة عربية', 'ARB-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر اللغة العربية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catEng)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catEng, 'English ' + CAST(@gradeOrder AS VARCHAR), N'لغة إنجليزية', 'ENG-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر اللغة الإنجليزية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catMath)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catMath, 'Mathematics ' + CAST(@gradeOrder AS VARCHAR), N'رياضيات', 'MATH-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الرياضيات للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catSci)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catSci, 'Science ' + CAST(@gradeOrder AS VARCHAR), N'علوم', 'SCI-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر العلوم للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catSoc)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catSoc, 'Social Studies ' + CAST(@gradeOrder AS VARCHAR), N'دراسات اجتماعية', 'SOC-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الدراسات الاجتماعية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catRel)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catRel, 'Religion ' + CAST(@gradeOrder AS VARCHAR), N'تربية دينية', 'REL-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر التربية الدينية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catCS)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catCS, 'Computer Science ' + CAST(@gradeOrder AS VARCHAR), N'حاسب آلي', 'CS-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الحاسب الآلي للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catPE)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catPE, 'Physical Education ' + CAST(@gradeOrder AS VARCHAR), N'تربية رياضية', 'PE-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر التربية الرياضية للصف ' + CAST(@gradeOrder AS NVARCHAR));
    END

    -- Secondary School (Grade 10+)
    IF @gradeOrder >= 10
    BEGIN
        -- Core
        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catArb)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catArb, 'Arabic ' + CAST(@gradeOrder AS VARCHAR), N'لغة عربية', 'ARB-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر اللغة العربية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catEng)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catEng, 'English ' + CAST(@gradeOrder AS VARCHAR), N'لغة إنجليزية', 'ENG-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر اللغة الإنجليزية للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catMath)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catMath, 'Mathematics ' + CAST(@gradeOrder AS VARCHAR), N'رياضيات', 'MATH-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الرياضيات للصف ' + CAST(@gradeOrder AS NVARCHAR));

        -- Science Track
        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catPhy)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catPhy, 'Physics ' + CAST(@gradeOrder AS VARCHAR), N'فيزياء', 'PHY-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الفيزياء للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catChe)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catChe, 'Chemistry ' + CAST(@gradeOrder AS VARCHAR), N'كيمياء', 'CHE-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الكيمياء للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catBio)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catBio, 'Biology ' + CAST(@gradeOrder AS VARCHAR), N'أحياء', 'BIO-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الأحياء للصف ' + CAST(@gradeOrder AS NVARCHAR));

        -- Arts Track
        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catHis)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catHis, 'History ' + CAST(@gradeOrder AS VARCHAR), N'تاريخ', 'HIS-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر التاريخ للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catGeo)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catGeo, 'Geography ' + CAST(@gradeOrder AS VARCHAR), N'جغرافيا', 'GEO-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الجغرافيا للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catPhi)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catPhi, 'Philosophy ' + CAST(@gradeOrder AS VARCHAR), N'فلسفة', 'PHI-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الفلسفة للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catPsy)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catPsy, 'Psychology ' + CAST(@gradeOrder AS VARCHAR), N'علم نفس', 'PSY-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر علم النفس للصف ' + CAST(@gradeOrder AS NVARCHAR));

        IF NOT EXISTS (SELECT 1 FROM subjects WHERE GradeId = @gradeId AND SubjectCategoryId = @catGel)
            INSERT INTO subjects (GradeId, SubjectCategoryId, Name, NameAr, Code, IsActive, Description)
            VALUES (@gradeId, @catGel, 'Geology ' + CAST(@gradeOrder AS VARCHAR), N'جيولوجيا', 'GEL-' + CAST(@gradeOrder AS VARCHAR), 1, N'مقرر الجيولوجيا للصف ' + CAST(@gradeOrder AS NVARCHAR));
    END

    FETCH NEXT FROM gradeCur INTO @gradeId, @gradeOrder;
END

CLOSE gradeCur;
DEALLOCATE gradeCur;

PRINT '[Seeder] Subjects seeded across all grades.';

-- ==============================================================
-- 8.  CLASSES  (2 sections per grade = 24 classes)
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM classes WHERE Name = 'Class 1A')
BEGIN
    INSERT INTO classes (GradeId, Name, MaxCapacity, AcademicYear, IsActive)
    SELECT g.GradeId,
           'Class ' + CAST(g.[Order] AS VARCHAR) + sec.SectionLetter,
           35,
           2026,
           1
    FROM grades g
    CROSS JOIN (VALUES ('A'), ('B')) AS sec(SectionLetter);
    PRINT '[Seeder] 24 classes seeded (2 sections per grade).';
END

-- ==============================================================
-- 9.  TEACHING ASSIGNMENTS
--     Assign each teacher to 2 classes for their specialization
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM teaching_assignments)
BEGIN
    -- Math teacher → Grade 1 classes
    DECLARE @mathTeacherId  INT = (SELECT TeacherId FROM teachers t INNER JOIN users u ON u.UserId = t.UserId WHERE u.Email = 'ahmed.mahmoud@masarak.com');
    DECLARE @arabTeacherId  INT = (SELECT TeacherId FROM teachers t INNER JOIN users u ON u.UserId = t.UserId WHERE u.Email = 'fatima.ibrahim@masarak.com');
    DECLARE @sciTeacherId   INT = (SELECT TeacherId FROM teachers t INNER JOIN users u ON u.UserId = t.UserId WHERE u.Email = 'mohamed.abdel@masarak.com');
    DECLARE @engTeacherId   INT = (SELECT TeacherId FROM teachers t INNER JOIN users u ON u.UserId = t.UserId WHERE u.Email = 'nora.khaled@masarak.com');
    DECLARE @hisTeacherId   INT = (SELECT TeacherId FROM teachers t INNER JOIN users u ON u.UserId = t.UserId WHERE u.Email = 'omar.hussam@masarak.com');
    DECLARE @phyTeacherId   INT = (SELECT TeacherId FROM teachers t INNER JOIN users u ON u.UserId = t.UserId WHERE u.Email = 'karim.walid@masarak.com');
    DECLARE @cheTeacherId   INT = (SELECT TeacherId FROM teachers t INNER JOIN users u ON u.UserId = t.UserId WHERE u.Email = 'mona.rami@masarak.com');
    DECLARE @bioTeacherId   INT = (SELECT TeacherId FROM teachers t INNER JOIN users u ON u.UserId = t.UserId WHERE u.Email = 'yousef.sami@masarak.com');
    DECLARE @csTeacherId    INT = (SELECT TeacherId FROM teachers t INNER JOIN users u ON u.UserId = t.UserId WHERE u.Email = 'rana.hamdi@masarak.com');

    -- Grade 1 Math → Class 1A
    INSERT INTO teaching_assignments (TeacherId, ClassId, SubjectId, AcademicYear, IsActive, CreatedAt)
    SELECT @mathTeacherId,
           (SELECT ClassId FROM classes WHERE Name = 'Class 1A'),
           (SELECT SubjectId FROM subjects s INNER JOIN grades g ON g.GradeId = s.GradeId WHERE g.[Order]=1 AND s.SubjectCategoryId = @catMath),
           2026, 1, GETUTCDATE()
    WHERE @mathTeacherId IS NOT NULL;

    -- Grade 1 Arabic → Class 1B
    INSERT INTO teaching_assignments (TeacherId, ClassId, SubjectId, AcademicYear, IsActive, CreatedAt)
    SELECT @arabTeacherId,
           (SELECT ClassId FROM classes WHERE Name = 'Class 1B'),
           (SELECT SubjectId FROM subjects s INNER JOIN grades g ON g.GradeId = s.GradeId WHERE g.[Order]=1 AND s.SubjectCategoryId = @catArb),
           2026, 1, GETUTCDATE()
    WHERE @arabTeacherId IS NOT NULL;

    -- Grade 7 Physics → Class 7A
    INSERT INTO teaching_assignments (TeacherId, ClassId, SubjectId, AcademicYear, IsActive, CreatedAt)
    SELECT @phyTeacherId,
           (SELECT ClassId FROM classes WHERE Name = 'Class 7A'),
           (SELECT SubjectId FROM subjects s INNER JOIN grades g ON g.GradeId = s.GradeId WHERE g.[Order]=7 AND s.SubjectCategoryId = @catPhy),
           2026, 1, GETUTCDATE()
    WHERE @phyTeacherId IS NOT NULL;

    -- Grade 10 Chemistry → Class 10A
    INSERT INTO teaching_assignments (TeacherId, ClassId, SubjectId, AcademicYear, IsActive, CreatedAt)
    SELECT @cheTeacherId,
           (SELECT ClassId FROM classes WHERE Name = 'Class 10A'),
           (SELECT SubjectId FROM subjects s INNER JOIN grades g ON g.GradeId = s.GradeId WHERE g.[Order]=10 AND s.SubjectCategoryId = @catChe),
           2026, 1, GETUTCDATE()
    WHERE @cheTeacherId IS NOT NULL;

    -- Grade 12 CS → Class 12A
    INSERT INTO teaching_assignments (TeacherId, ClassId, SubjectId, AcademicYear, IsActive, CreatedAt)
    SELECT @csTeacherId,
           (SELECT ClassId FROM classes WHERE Name = 'Class 12A'),
           (SELECT SubjectId FROM subjects s INNER JOIN grades g ON g.GradeId = s.GradeId WHERE g.[Order]=12 AND s.SubjectCategoryId = @catCS),
           2026, 1, GETUTCDATE()
    WHERE @csTeacherId IS NOT NULL;

    PRINT '[Seeder] Teaching assignments seeded.';
END

-- ==============================================================
-- 10.  STUDENTS  (50 students across all grades)
--      Spread creation dates across 12 months for growth chart
-- ==============================================================
DECLARE @studentInserts TABLE (
    FullName       NVARCHAR(150),
    Email          VARCHAR(255),
    Phone          VARCHAR(30),
    GradeOrder     INT,
    CreatedMonthsAgo INT   -- for realistic growth trend
);

INSERT INTO @studentInserts VALUES
-- Grade 1  (5 students)
(N'محمد أحمد علي',         'student01@masarak.com', '+20-111-2001001', 1, 12),
(N'فاطمة حسن محمد',        'student02@masarak.com', '+20-111-2001002', 1, 11),
(N'يوسف كمال سلامة',       'student03@masarak.com', '+20-111-2001003', 1, 10),
(N'مريم طارق الشريف',      'student04@masarak.com', '+20-111-2001004', 1, 9),
(N'عمر سعيد الجوهري',      'student05@masarak.com', '+20-111-2001005', 1, 8),
-- Grade 2
(N'لمياء وليد حمدي',       'student06@masarak.com', '+20-111-2002001', 2, 11),
(N'إبراهيم محمود سالم',    'student07@masarak.com', '+20-111-2002002', 2, 10),
(N'نادية رامي عاطف',       'student08@masarak.com', '+20-111-2002003', 2, 9),
(N'حسام عزت بكر',          'student09@masarak.com', '+20-111-2002004', 2, 7),
-- Grade 3
(N'سلمى أشرف منير',        'student10@masarak.com', '+20-111-2003001', 3, 11),
(N'كريم شادي فتحي',        'student11@masarak.com', '+20-111-2003002', 3, 9),
(N'نور الهدى صالح',        'student12@masarak.com', '+20-111-2003003', 3, 8),
-- Grade 4
(N'آدم جلال الدسوقي',      'student13@masarak.com', '+20-111-2004001', 4, 10),
(N'ليلى حسام رشاد',        'student14@masarak.com', '+20-111-2004002', 4, 8),
(N'زياد منير البدوي',       'student15@masarak.com', '+20-111-2004003', 4, 7),
-- Grade 5
(N'رهف سامر الحلبي',       'student16@masarak.com', '+20-111-2005001', 5, 9),
(N'بسمة رفعت الدباغ',      'student17@masarak.com', '+20-111-2005002', 5, 7),
(N'أنس أمجد القاضي',       'student18@masarak.com', '+20-111-2005003', 5, 6),
-- Grade 6
(N'ياسمين فيصل الحمصي',   'student19@masarak.com', '+20-111-2006001', 6, 8),
(N'معاذ سلطان الأمير',     'student20@masarak.com', '+20-111-2006002', 6, 6),
(N'جنى عماد حداد',         'student21@masarak.com', '+20-111-2006003', 6, 5),
-- Grade 7
(N'حمزة وائل الزهراني',    'student22@masarak.com', '+20-111-2007001', 7, 8),
(N'ريما باسل الخوري',      'student23@masarak.com', '+20-111-2007002', 7, 7),
(N'تيم نزار الأحمدي',      'student24@masarak.com', '+20-111-2007003', 7, 5),
(N'دانا رياض الخليل',      'student25@masarak.com', '+20-111-2007004', 7, 4),
-- Grade 8
(N'أمير فارس الحربي',      'student26@masarak.com', '+20-111-2008001', 8, 7),
(N'سيرين عادل القاسم',     'student27@masarak.com', '+20-111-2008002', 8, 5),
(N'رامي زياد الطحان',      'student28@masarak.com', '+20-111-2008003', 8, 4),
-- Grade 9
(N'هناء مصطفى جابر',       'student29@masarak.com', '+20-111-2009001', 9, 6),
(N'محمود صلاح الجبر',      'student30@masarak.com', '+20-111-2009002', 9, 5),
(N'إسراء بلال منصور',      'student31@masarak.com', '+20-111-2009003', 9, 3),
-- Grade 10
(N'عبدالله ماهر نصر',      'student32@masarak.com', '+20-111-2010001', 10, 6),
(N'شهد حافظ الأشقر',       'student33@masarak.com', '+20-111-2010002', 10, 5),
(N'قيس صبحي السيد',        'student34@masarak.com', '+20-111-2010003', 10, 4),
(N'ديمة نادر الصالح',      'student35@masarak.com', '+20-111-2010004', 10, 3),
-- Grade 11
(N'عدنان لؤي البطاط',      'student36@masarak.com', '+20-111-2011001', 11, 5),
(N'ألاء رامز الياس',        'student37@masarak.com', '+20-111-2011002', 11, 4),
(N'بلال ثائر الحسن',        'student38@masarak.com', '+20-111-2011003', 11, 3),
(N'إيناس نبيل عوض',        'student39@masarak.com', '+20-111-2011004', 11, 2),
-- Grade 12
(N'خالد عمار الزيات',      'student40@masarak.com', '+20-111-2012001', 12, 5),
(N'صبا مراد الجمال',        'student41@masarak.com', '+20-111-2012002', 12, 4),
(N'عبير حسن الغزاوي',      'student42@masarak.com', '+20-111-2012003', 12, 3),
(N'سعد توفيق الصواف',      'student43@masarak.com', '+20-111-2012004', 12, 2),
(N'لانا شريف العلمي',      'student44@masarak.com', '+20-111-2012005', 12, 1),
-- Extra students added recently (for growth trend spike)
(N'طه وسام البلوشي',       'student45@masarak.com', '+20-111-2001006', 1, 2),
(N'غدير أنس الكواز',       'student46@masarak.com', '+20-111-2002005', 2, 2),
(N'رافت يحيى الأشوح',      'student47@masarak.com', '+20-111-2003004', 3, 1),
(N'هبة جمال السريحي',      'student48@masarak.com', '+20-111-2004004', 4, 1),
(N'مالك نضال الحريري',     'student49@masarak.com', '+20-111-2005004', 5, 1),
(N'وسام ضياء العثماني',    'student50@masarak.com', '+20-111-2006004', 6, 1);

-- Insert student users
INSERT INTO users (RoleId, FullName, Email, PasswordHash, Phone, Country, CreatedAt, IsActive, EmailConfirmed, FailedLoginCount)
SELECT @studentRoleId, si.FullName, si.Email,
       'SEED_PLACEHOLDER_RUN_APP_TO_SET_REAL_HASH',
       si.Phone, 'EG',
       DATEADD(MONTH, -si.CreatedMonthsAgo, GETUTCDATE()),
       1, 1, 0
FROM @studentInserts si
WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.Email = si.Email);

-- Insert student profiles
INSERT INTO students (UserId, GradeId, EnrollmentDate, AcademicStatus)
SELECT u.UserId,
       g.GradeId,
       DATEADD(MONTH, -si.CreatedMonthsAgo, GETUTCDATE()),
       'Active'
FROM @studentInserts si
INNER JOIN users u ON u.Email = si.Email
INNER JOIN grades g ON g.[Order] = si.GradeOrder
WHERE NOT EXISTS (SELECT 1 FROM students st WHERE st.UserId = u.UserId);

PRINT '[Seeder] 50 student accounts seeded with varied registration dates for growth chart.';

-- ==============================================================
-- 11.  STUDENT ENROLLMENTS INTO CLASSES
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM student_classes)
BEGIN
    INSERT INTO student_classes (StudentId, ClassId, AcademicYear, EnrollmentType, EnrolledAt, IsActive)
    SELECT s.StudentId,
           c.ClassId,
           2026,
           1, -- 1 = FullClass enum
           s.EnrollmentDate,
           1
    FROM students s
    INNER JOIN grades g ON g.GradeId = s.GradeId
    INNER JOIN classes c ON c.GradeId = g.GradeId AND c.Name LIKE 'Class ' + CAST(g.[Order] AS VARCHAR) + 'A'
    WHERE NOT EXISTS (
        SELECT 1 FROM student_classes sc
        WHERE sc.StudentId = s.StudentId AND sc.AcademicYear = 2026
    );
    PRINT '[Seeder] Student class enrollments seeded.';
END

-- ==============================================================
-- 12.  SUBSCRIPTIONS & PAYMENTS
--      Payment.SubscriptionId is a required FK, so we insert
--      subscriptions first, then payments linked by SubscriptionId.
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM subscriptions)
BEGIN
    DECLARE @monthlyPlanId INT = (SELECT PlanId FROM plans WHERE Type = 'Monthly');
    DECLARE @fullPlanId    INT = (SELECT PlanId FROM plans WHERE Type = 'FullCurriculum');

    -- 1. Insert subscriptions
    INSERT INTO subscriptions (UserId, PlanId, Status, StartDate, EndDate, ActivationMethod, AdminNote, CreatedAt)
    SELECT u.UserId,
           CASE WHEN ROW_NUMBER() OVER (ORDER BY u.UserId) % 3 = 0
                THEN @fullPlanId ELSE @monthlyPlanId END,
           'Active',
           DATEADD(MONTH, -1, GETUTCDATE()),
           DATEADD(MONTH,  1, GETUTCDATE()),
           'AdminManual',
           N'اشتراك تجريبي للاختبار',
           GETUTCDATE()
    FROM users u
    WHERE u.RoleId = @studentRoleId;

    -- 2. Insert one payment per subscription (SubscriptionId known now)
    INSERT INTO payments (SubscriptionId, Amount, Currency, Status, Provider, Gateway, GatewayTxnId, PaidAt, CreatedAt)
    SELECT s.SubscriptionId,
           CASE WHEN s.PlanId = @fullPlanId THEN 24.99 ELSE 9.99 END,
           'USD',
           'Completed',
           'Manual',
           'Manual',
           'SEED-' + CAST(s.SubscriptionId AS VARCHAR),
           DATEADD(MONTH, -1, GETUTCDATE()),
           GETUTCDATE()
    FROM subscriptions s;

    PRINT '[Seeder] Subscriptions and payments seeded for 50 students.';
END

-- ==============================================================
-- 13.  NOTIFICATIONS  (15+ realistic notifications for Admin)
-- ==============================================================
DECLARE @adminUserId INT = (SELECT UserId FROM users WHERE Email = 'admin@masarak.com');

IF @adminUserId IS NOT NULL AND NOT EXISTS (SELECT 1 FROM notifications WHERE UserId = @adminUserId AND Title = N'طلب تسجيل معلم جديد: أحمد محمود')
BEGIN
    -- We assign them to a generic adminUserId=1 (since C# seeder creates it first usually)
    INSERT INTO notifications (UserId, Title, Body, Type, IsRead, CreatedAt)
    VALUES
    (1, N'طلب انضمام معلم جديد', N'المعلم أحمد حسن قدم طلب انضمام للمنصة', 'SystemAlert', 0, DATEADD(hour, -2, GETUTCDATE()));

    INSERT INTO notifications (UserId, Type, Title, Body, ActionUrl, Channel, IsRead, CreatedAt)
    VALUES
    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: أحمد محمود',
     N'تقدم أحمد محمود السيد للانضمام كمعلم رياضيات. يرجى مراجعة ملفه الشخصي والموافقة أو الرفض.',
     '/admin/teachers/pending', 'InApp', 0, DATEADD(MINUTE, -5,  GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: سارة فارس',
     N'تقدمت سارة مصطفى فارس للانضمام كمعلمة جغرافيا. في انتظار مراجعة المؤهلات.',
     '/admin/teachers/pending', 'InApp', 0, DATEADD(MINUTE, -30, GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: كريم وليد',
     N'تقدم كريم وليد زكي بطلب تدريس مادة الفيزياء للمرحلة الثانوية. يحمل ماجستير فيزياء.',
     '/admin/teachers/pending', 'InApp', 0, DATEADD(HOUR,  -1,  GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: رنا حمدي',
     N'تقدمت رنا حمدي إسماعيل للتدريس في تخصص الحاسب الآلي والبرمجة.',
     '/admin/teachers/pending', 'InApp', 0, DATEADD(HOUR,  -2,  GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: منى رامي',
     N'تقدمت منى رامي شحاتة لتدريس مادة الكيمياء. لديها خبرة في إعداد التجارب الافتراضية.',
     '/admin/teachers/pending', 'InApp', 0, DATEADD(HOUR,  -3,  GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: عمر حسام',
     N'تقدم عمر حسام الدين لتدريس مادة التاريخ. متخصص في الحضارة الإسلامية.',
     '/admin/teachers/pending', 'InApp', 0, DATEADD(HOUR,  -5,  GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: نورا خالد',
     N'تقدمت نورا خالد منصور لتدريس اللغة الإنجليزية. حاصلة على شهادة TEFL الدولية.',
     '/admin/teachers/pending', 'InApp', 0, DATEADD(HOUR,  -6,  GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: إيمان صبري',
     N'تقدمت إيمان صبري درويش لتدريس اللغة العربية للمرحلة الابتدائية.',
     '/admin/teachers/pending', 'InApp', 0, DATEADD(HOUR,  -8,  GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: طارق عصام',
     N'تقدم طارق عصام نبيل لتدريس الرياضيات للثانوية العامة. متخصص في حساب التفاضل والتكامل.',
     '/admin/teachers/pending', 'InApp', 1, DATEADD(HOUR, -10,  GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'طلب تسجيل معلم جديد: هالة نادر',
     N'تقدمت هالة نادر مكرم لتدريس الإنجليزية. تُعدّ الطلاب لاختبارات IELTS وTOEFL.',
     '/admin/teachers/pending', 'InApp', 1, DATEADD(HOUR, -12,  GETUTCDATE())),

    -- Performance alerts
    (@adminUserId, 'LowPerformanceAlert', N'تنبيه أداء: انخفاض في نسبة الحضور',
     N'لاحظ النظام انخفاضًا في نسبة حضور 8 طلاب في الفصل الدراسي الأول إلى أقل من 70%. يُنصح بمتابعة أولياء الأمور.',
     '/admin/reports/attendance', 'InApp', 0, DATEADD(DAY, -1, GETUTCDATE())),

    (@adminUserId, 'LowPerformanceAlert', N'تنبيه أداء: انخفاض درجات في الرياضيات',
     N'متوسط درجات الاختبارات في مادة الرياضيات لصف الأول الإعدادي انخفض إلى 58%. يُقترح مراجعة أسلوب التدريس.',
     '/admin/reports/grades', 'InApp', 0, DATEADD(DAY, -2, GETUTCDATE())),

    -- Payment / subscription alerts
    (@adminUserId, 'PaymentFailed', N'فشل تجديد اشتراك طالب',
     N'فشلت محاولة تجديد اشتراك الطالب "عبدالله ماهر نصر" تلقائيًا. يرجى التواصل مع ولي الأمر.',
     '/admin/subscriptions', 'InApp', 0, DATEADD(DAY, -1, GETUTCDATE())),

    -- Calendar / schedule alerts
    (@adminUserId, 'SubscriptionExpiring', N'تنبيه التقويم الأكاديمي',
     N'حان موعد مزامنة جدول الفصل الدراسي الثاني. يرجى مراجعة الجداول وتحديثها قبل بدء الفصل.',
     '/admin/calendar', 'InApp', 0, DATEADD(DAY, -3, GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'تسجيل طالب جديد: وسام العثماني',
     N'انضم وسام ضياء العثماني للمنصة للتو. يرجى تفعيل اشتراكه وتعيينه في الفصل المناسب.',
     '/admin/students', 'InApp', 0, DATEADD(HOUR, -2, GETUTCDATE())),

    (@adminUserId, 'NewUserRegistered', N'تسجيل طالب جديد: لانا العلمي',
     N'انضمت لانا شريف العلمي للمنصة. طالبة جديدة في الصف الثاني عشر.',
     '/admin/students', 'InApp', 0, DATEADD(HOUR, -4, GETUTCDATE())),

    (@adminUserId, 'SubscriptionActivated', N'اكتمال بيانات الفصل الدراسي الأول',
     N'تم اكتمال بيانات تسجيل جميع الطلاب للفصل الدراسي الأول لعام 2025/2026. يمكنك الآن مراجعة التقارير الإجمالية.',
     '/admin/dashboard', 'InApp', 1, DATEADD(DAY, -7, GETUTCDATE()));

    INSERT INTO notifications (UserId, Title, Body, Type, IsRead, CreatedAt)
    VALUES (1, N'تحديث النظام', N'تم تحديث خوادم المنصة بنجاح', 'SystemAlert', 1, DATEADD(day, -5, GETUTCDATE()));

    PRINT '[Seeder] 17 admin notifications seeded (teacher applications, alerts, calendar).';
END

-- ==============================================================
-- 14.  TEACHER NOTIFICATIONS (for teacher users)
-- ==============================================================
DECLARE @teacher1UserId INT = (SELECT u.UserId FROM users u WHERE u.Email = 'ahmed.mahmoud@masarak.com');
DECLARE @teacher2UserId INT = (SELECT u.UserId FROM users u WHERE u.Email = 'fatima.ibrahim@masarak.com');
DECLARE @teacher3UserId INT = (SELECT u.UserId FROM users u WHERE u.Email = 'karim.walid@masarak.com');

IF @teacher1UserId IS NOT NULL AND NOT EXISTS (SELECT 1 FROM notifications WHERE UserId = @teacher1UserId)
BEGIN
    INSERT INTO notifications (UserId, Type, Title, Body, ActionUrl, Channel, IsRead, CreatedAt)
    VALUES
    (@teacher1UserId, 'NewEnrollment', N'طالب جديد انضم إلى فصلك',
     N'انضم الطالب "محمد أحمد علي" إلى فصل الرياضيات 1A. يمكنك الاطلاع على ملفه الأكاديمي.',
     '/teacher/classes', 'InApp', 0, DATEADD(HOUR, -3, GETUTCDATE())),

    (@teacher1UserId, 'SubmissionReceived', N'تم استلام واجب جديد',
     N'استلم النظام 18 ورقة إجابة لاختبار "الأعداد الصحيحة وعمليات الجمع". يمكنك البدء في التصحيح.',
     '/teacher/submissions', 'InApp', 0, DATEADD(HOUR, -1, GETUTCDATE())),

    (@teacher2UserId, 'NewEnrollment', N'انضم طالب جديد لفصلك',
     N'انضمت "فاطمة حسن محمد" لفصل اللغة العربية 1B.',
     '/teacher/classes', 'InApp', 0, DATEADD(HOUR, -5, GETUTCDATE())),

    (@teacher3UserId, 'ExamFullyGraded', N'تم اكتمال تصحيح الاختبار',
     N'تم تصحيح جميع أوراق اختبار "قوانين نيوتن للحركة" آليًا. يرجى مراجعة الدرجات المعلقة.',
     '/teacher/exams', 'InApp', 1, DATEADD(DAY, -1, GETUTCDATE()));

    PRINT '[Seeder] Teacher notifications seeded.';
END

-- ==============================================================
-- 15.  ANALYTICS DASHBOARD SNAPSHOTS
--      (Platform-level snapshot to power the growth trend chart)
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM analytics_snapshots WHERE Scope = 'Platform')
BEGIN
    INSERT INTO analytics_snapshots (Scope, ScopeEntityId, DataJson, GeneratedAt, ExpiresAt)
    VALUES
    -- Platform-wide snapshot (used by admin dashboard chart)
    ('Platform', NULL,
    N'{
      "totalStudents": 50,
      "activeTeachers": 15,
      "totalCourses": 96,
      "totalRevenue": 1247.50,
      "activeSubscriptions": 50,
      "userGrowthTrend": [
        {"month": "2025-08", "label": "أغسطس",    "newStudents": 3,  "newTeachers": 1},
        {"month": "2025-09", "label": "سبتمبر",   "newStudents": 5,  "newTeachers": 2},
        {"month": "2025-10", "label": "أكتوبر",   "newStudents": 4,  "newTeachers": 2},
        {"month": "2025-11", "label": "نوفمبر",   "newStudents": 6,  "newTeachers": 3},
        {"month": "2025-12", "label": "ديسمبر",   "newStudents": 4,  "newTeachers": 1},
        {"month": "2026-01", "label": "يناير",    "newStudents": 7,  "newTeachers": 2},
        {"month": "2026-02", "label": "فبراير",   "newStudents": 5,  "newTeachers": 1},
        {"month": "2026-03", "label": "مارس",     "newStudents": 4,  "newTeachers": 1},
        {"month": "2026-04", "label": "أبريل",    "newStudents": 5,  "newTeachers": 1},
        {"month": "2026-05", "label": "مايو",     "newStudents": 3,  "newTeachers": 0},
        {"month": "2026-06", "label": "يونيو",    "newStudents": 2,  "newTeachers": 0},
        {"month": "2026-07", "label": "يوليو",    "newStudents": 2,  "newTeachers": 1}
      ],
      "gradeDistribution": [
        {"grade": "Grade 1",  "students": 6},
        {"grade": "Grade 2",  "students": 5},
        {"grade": "Grade 3",  "students": 4},
        {"grade": "Grade 4",  "students": 4},
        {"grade": "Grade 5",  "students": 4},
        {"grade": "Grade 6",  "students": 4},
        {"grade": "Grade 7",  "students": 4},
        {"grade": "Grade 8",  "students": 3},
        {"grade": "Grade 9",  "students": 3},
        {"grade": "Grade 10", "students": 4},
        {"grade": "Grade 11", "students": 4},
        {"grade": "Grade 12", "students": 5}
      ],
      "subscriptionRevenue": {
        "Monthly": 449.55,
        "FullCurriculum": 797.95
      }
    }',
    GETUTCDATE(),
    DATEADD(HOUR, 24, GETUTCDATE())),

    -- Grade-level snapshots
    ('Grade', (SELECT GradeId FROM grades WHERE [Order] = 12),
    N'{"gradeId":12,"gradeName":"Grade 12","totalStudents":5,"avgAttendance":88.4,"avgExamScore":74.2,"activeAssignments":3}',
    GETUTCDATE(), DATEADD(HOUR, 24, GETUTCDATE())),

    ('Grade', (SELECT GradeId FROM grades WHERE [Order] = 10),
    N'{"gradeId":10,"gradeName":"Grade 10","totalStudents":4,"avgAttendance":91.0,"avgExamScore":79.5,"activeAssignments":2}',
    GETUTCDATE(), DATEADD(HOUR, 24, GETUTCDATE()));

    PRINT '[Seeder] Analytics dashboard snapshots seeded (Platform + 2 grade snapshots).';
END

-- ==============================================================
-- 16.  PERFORMANCE ALERTS  (for testing admin alert panel)
-- ==============================================================
DECLARE @st1UserId INT = (SELECT u.UserId FROM users u WHERE u.Email = 'student01@masarak.com');
DECLARE @st2UserId INT = (SELECT u.UserId FROM users u WHERE u.Email = 'student09@masarak.com');
DECLARE @st3UserId INT = (SELECT u.UserId FROM users u WHERE u.Email = 'student22@masarak.com');
DECLARE @mathSubj1 INT = (SELECT s.SubjectId FROM subjects s INNER JOIN grades g ON g.GradeId = s.GradeId WHERE g.[Order]=1 AND s.SubjectCategoryId = @catMath);
DECLARE @sciSubj2  INT = (SELECT s.SubjectId FROM subjects s INNER JOIN grades g ON g.GradeId = s.GradeId WHERE g.[Order]=2 AND s.SubjectCategoryId = @catSci);
DECLARE @phySubj7  INT = (SELECT s.SubjectId FROM subjects s INNER JOIN grades g ON g.GradeId = s.GradeId WHERE g.[Order]=7 AND s.SubjectCategoryId = @catPhy);

IF @st1UserId IS NOT NULL AND NOT EXISTS (SELECT 1 FROM performance_alerts WHERE StudentUserId = @st1UserId)
BEGIN
    INSERT INTO performance_alerts (StudentUserId, SubjectId, AlertType, Message, TriggerValue, Threshold, IsResolved, CreatedAt)
    VALUES
    (@st1UserId, @mathSubj1, 'LowAttendance',
     N'نسبة حضور الطالب "محمد أحمد علي" في الرياضيات انخفضت إلى 62%. الحد الأدنى المقبول هو 75%.',
     62.0, 75.0, 0, DATEADD(DAY, -3, GETUTCDATE())),

    (@st2UserId, @sciSubj2, 'LowExamScore',
     N'حصل الطالب "حسام عزت بكر" على درجة 45% في آخر اختبار علوم، وهي أقل من الحد الأدنى 50%.',
     45.0, 50.0, 0, DATEADD(DAY, -2, GETUTCDATE())),

    (@st3UserId, @phySubj7, 'MissedAssignments',
     N'الطالب "حمزة وائل الزهراني" لم يسلّم 3 واجبات فيزياء متتالية.',
     3.0, 1.0, 0, DATEADD(DAY, -1, GETUTCDATE()));

    PRINT '[Seeder] 3 performance alerts seeded.';
END

-- ==============================================================
-- 17.  STUDENT PERFORMANCE RECORDS
--      (historical data so admin dashboard shows real numbers)
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM student_performance)
BEGIN
    -- Seed performance records for a selection of students
    DECLARE @perfInserts TABLE (Email VARCHAR(255), GradeOrder INT, SubjCatId INT, AvgAssignment DECIMAL(5,2), AvgExam DECIMAL(5,2), AttendanceRate DECIMAL(5,2), FinalGrade DECIMAL(5,2), GradeLetter CHAR(2));

    INSERT INTO @perfInserts VALUES
    ('student01@masarak.com', 1, @catMath, 82.0, 78.5, 62.0, 75.2, 'B'),
    ('student01@masarak.com', 1, @catArb,  90.0, 87.0, 95.0, 89.0, 'A'),
    ('student02@masarak.com', 1, @catMath, 76.5, 80.0, 88.0, 79.5, 'B'),
    ('student09@masarak.com', 2, @catSci,  55.0, 45.0, 70.0, 52.0, 'D'),
    ('student22@masarak.com', 7, @catPhy,  65.0, 70.0, 75.0, 68.0, 'C'),
    ('student32@masarak.com', 10, @catChe, 88.0, 85.0, 92.0, 87.5, 'A'),
    ('student40@masarak.com', 12, @catCS,  95.0, 91.0, 98.0, 93.5, 'A');

    INSERT INTO student_performance (StudentId, SubjectId, ClassId, AcademicYear, TotalExamsTaken, AvgAssignment, AvgExam, AttendanceRate, FinalGrade, GradeLetter, UpdatedAt)
    SELECT
        st.StudentId,
        subj.SubjectId,
        c.ClassId,
        '2025-2026',
        3,
        pi.AvgAssignment,
        pi.AvgExam,
        pi.AttendanceRate,
        pi.FinalGrade,
        pi.GradeLetter,
        GETUTCDATE()
    FROM @perfInserts pi
    INNER JOIN users u ON u.Email = pi.Email
    INNER JOIN students st ON st.UserId = u.UserId
    INNER JOIN grades g ON g.GradeId = st.GradeId AND g.[Order] = pi.GradeOrder
    INNER JOIN subjects subj ON subj.GradeId = g.GradeId AND subj.SubjectCategoryId = pi.SubjCatId
    INNER JOIN classes c ON c.GradeId = g.GradeId AND c.Name LIKE 'Class ' + CAST(g.[Order] AS VARCHAR) + 'A'
    WHERE NOT EXISTS (
        SELECT 1 FROM student_performance sp
        WHERE sp.StudentId = st.StudentId AND sp.SubjectId = subj.SubjectId AND sp.AcademicYear = '2025-2026'
    );

    PRINT '[Seeder] Student performance records seeded.';
END

-- ==============================================================
-- 18.  CHAT ROOMS (one per grade + teachers community)
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM chat_rooms)
BEGIN
    INSERT INTO chat_rooms (RoomType, GradeId, Name, IsActive)
    SELECT 'GradeCommunity', g.GradeId, g.Name + ' Community', 1
    FROM grades g;

    INSERT INTO chat_rooms (RoomType, GradeId, Name, IsActive)
    VALUES ('TeachersCommunity', NULL, 'Teachers Community', 1);

    PRINT '[Seeder] Chat rooms seeded (12 grade rooms + 1 teachers room).';
END

-- ==============================================================
-- 19.  STUDENT NOTIFICATIONS (sample for 5 students)
-- ==============================================================
DECLARE @stu1 INT = (SELECT u.UserId FROM users u WHERE u.Email = 'student01@masarak.com');
DECLARE @stu5 INT = (SELECT u.UserId FROM users u WHERE u.Email = 'student05@masarak.com');
DECLARE @stu32 INT = (SELECT u.UserId FROM users u WHERE u.Email = 'student32@masarak.com');

IF @stu1 IS NOT NULL AND NOT EXISTS (SELECT 1 FROM notifications WHERE UserId = @stu1)
BEGIN
    INSERT INTO notifications (UserId, Type, Title, Body, ActionUrl, Channel, IsRead, CreatedAt)
    VALUES
    (@stu1, 'AttendanceAlert',     N'تنبيه الحضور',
     N'انخفضت نسبة حضورك في مادة الرياضيات إلى 62%. يُرجى الالتزام بالحضور لتجنب الرسوب.',
     '/student/attendance', 'InApp', 0, DATEADD(HOUR, -6, GETUTCDATE())),

    (@stu1, 'NewAssignment',       N'واجب جديد: الأعداد الصحيحة',
     N'نشر معلمك واجبًا جديدًا في مادة الرياضيات. الموعد النهائي بعد أسبوع.',
     '/student/assignments', 'InApp', 0, DATEADD(HOUR, -2, GETUTCDATE())),

    (@stu5, 'ExamOpening',         N'اختبار الأحياء مفتوح الآن',
     N'بدأ اختبار "الخلايا والأنسجة" في مادة الأحياء. لديك 60 دقيقة لإتمامه.',
     '/student/exams', 'InApp', 0, DATEADD(HOUR, -1, GETUTCDATE())),

    (@stu32, 'SubscriptionExpiring',N'اشتراكك ينتهي قريبًا',
     N'ينتهي اشتراكك الحالي خلال 7 أيام. يُرجى التجديد للاستمرار في الوصول إلى المقررات.',
     '/student/subscription', 'InApp', 0, DATEADD(HOUR, -12, GETUTCDATE())),

    (@stu32, 'ExamGraded',         N'تم رصد درجة اختبار الكيمياء',
     N'حصلت على 88/100 في اختبار "التفاعلات الكيميائية". أحسنت!',
     '/student/grades', 'InApp', 1, DATEADD(DAY, -1, GETUTCDATE()));

    PRINT '[Seeder] Student notifications seeded.';
END

-- ==============================================================
-- 20.  AI PROMPT TEMPLATES
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM ai_prompt_templates WHERE [Key] = 'weakness_analysis')
BEGIN
    INSERT INTO ai_prompt_templates ([Key], SystemPrompt, UserPromptTemplate, MaxTokens, Temperature, UpdatedAt, UpdatedBy)
    VALUES
    ('weakness_analysis',
     'You are an educational analyst for Egyptian K-12 curriculum. Analyze student performance data and identify specific topic weaknesses. Respond only in JSON.',
     'Analyze this student''s performance data and return JSON.\nStudent context: {student_context_json}\nReturn ONLY valid JSON matching this schema: {schema}\nIdentify weak lessons, strong lessons, topics where the student makes errors, and provide 3 specific personalized recommendations referencing lesson names in {language}.',
     1000, 0.30, GETUTCDATE(), 'system'),

    ('parent_report',
     'You are a student academic advisor writing a monthly report for an Egyptian parent. Be encouraging, clear, and specific. Write in {language}.',
     'Student: {student_name}, Report month: {month}. Subject: {subject_name}. Analysis context: {analysis_context_json}. Write a 100-word narrative summary of the student''s performance in this specific subject for the parent.',
     800, 0.70, GETUTCDATE(), 'system'),

    ('teaching_suggestion',
     'You are a curriculum expert for Egyptian K-12 education. Provide concise, actionable teaching suggestions.',
     'Teacher subject: {subject_name}, Grade: {grade_name}, Student weak topics: {weak_topics_json}. Provide one targeted teaching suggestion and 3 specific action items.',
     500, 0.50, GETUTCDATE(), 'system');

    PRINT '[Seeder] AI prompt templates seeded.';
END

-- ==============================================================
-- 21. TEACHER SUBJECTS (Specializations / UI)
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM teacher_subjects)
BEGIN
    -- Link teachers to subject categories based on their text specialization
    INSERT INTO teacher_subjects (TeacherId, SubjectCategoryId)
    SELECT t.TeacherId, sc.SubjectCategoryId
    FROM teachers t
    INNER JOIN users u ON u.UserId = t.UserId
    INNER JOIN subject_categories sc ON sc.Name = t.Specialization;

    PRINT '[Seeder] Teacher specializations (teacher_subjects) seeded.';
END

-- ==============================================================
-- 22. SESSIONS (Class Schedules / Timetables)
-- ==============================================================
IF NOT EXISTS (SELECT 1 FROM sessions)
BEGIN
    -- Insert 4 weekly sessions per teaching assignment (1 month schedule)
    INSERT INTO sessions (AssignmentId, ClassId, Title, Description, ScheduledAt, DurationMinutes, Status, CreatedAt)
    SELECT ta.AssignmentId,
           ta.ClassId,
           'حصة ' + s.NameAr,
           N'حصة مجدولة في الجدول الدراسي - الأسبوع ' + CAST(v.WeekNum AS VARCHAR),
           DATEADD(DAY, (v.WeekNum - 1) * 7 + (ta.AssignmentId % 5), CAST(GETUTCDATE() AS DATE)),
           45,
           'Scheduled',
           GETUTCDATE()
    FROM teaching_assignments ta
    INNER JOIN subjects s ON s.SubjectId = ta.SubjectId
    CROSS JOIN (VALUES (1),(2),(3),(4)) AS v(WeekNum);

    PRINT '[Seeder] Sessions (Timetables) seeded for teaching assignments.';
END

-- ==============================================================
-- 23.  SUMMARY COUNTS  (verification query)
-- ==============================================================
PRINT '[Seeder] Masarak comprehensive seed data script executed.';
GO

-- ==============================================================
--  IMPORTANT NOTE ON PASSWORD HASHES
--  ─────────────────────────────────────────────────────────────
--  This script inserts a placeholder string for PasswordHash
--  ('SEED_PLACEHOLDER_RUN_APP_TO_SET_REAL_HASH') for all
--  non-admin users. We will now update them to match the admin
--  password hash so you can log in as any user with 'Admin@12345!'
-- ==============================================================

UPDATE users
SET PasswordHash = (SELECT TOP 1 PasswordHash FROM users WHERE Email='admin@masarak.com' AND PasswordHash <> 'SEED_PLACEHOLDER_RUN_APP_TO_SET_REAL_HASH')
WHERE PasswordHash = 'SEED_PLACEHOLDER_RUN_APP_TO_SET_REAL_HASH';

PRINT '[Seeder] Password hashes normalized. All users share the admin password.';
